version: '3.8'
services:
  docker-jenkins:
    image: ${IMAGE}
    ports:
      - 8080:8080
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd
